// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { ISecurityCouncil$Type } from "./ISecurityCouncil";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ISecurityCouncil"]: ISecurityCouncil$Type;
    ["contracts/zk-gov/l1-contracts/src/interfaces/ISecurityCouncil.sol:ISecurityCouncil"]: ISecurityCouncil$Type;
  }

  interface ContractTypesMap {
    ["ISecurityCouncil"]: GetContractReturnType<ISecurityCouncil$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/interfaces/ISecurityCouncil.sol:ISecurityCouncil"]: GetContractReturnType<
      ISecurityCouncil$Type["abi"]
    >;
  }
}
