// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ISecurityCouncil$Type {
  _format: "hh-sol-artifact-1";
  contractName: "ISecurityCouncil";
  sourceName: "contracts/zk-gov/l1-contracts/src/interfaces/ISecurityCouncil.sol";
  abi: [
    {
      inputs: [
        {
          internalType: "bytes32";
          name: "_id";
          type: "bytes32";
        },
        {
          internalType: "address[]";
          name: "_signers";
          type: "address[]";
        },
        {
          internalType: "bytes[]";
          name: "_signatures";
          type: "bytes[]";
        },
      ];
      name: "approveUpgradeSecurityCouncil";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "uint256";
          name: "_validUntil";
          type: "uint256";
        },
        {
          internalType: "address[]";
          name: "_signers";
          type: "address[]";
        },
        {
          internalType: "bytes[]";
          name: "_signatures";
          type: "bytes[]";
        },
      ];
      name: "hardFreeze";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "uint256";
          name: "_threshold";
          type: "uint256";
        },
        {
          internalType: "uint256";
          name: "_validUntil";
          type: "uint256";
        },
        {
          internalType: "address[]";
          name: "_signers";
          type: "address[]";
        },
        {
          internalType: "bytes[]";
          name: "_signatures";
          type: "bytes[]";
        },
      ];
      name: "setSoftFreezeThreshold";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "uint256";
          name: "_validUntil";
          type: "uint256";
        },
        {
          internalType: "address[]";
          name: "_signers";
          type: "address[]";
        },
        {
          internalType: "bytes[]";
          name: "_signatures";
          type: "bytes[]";
        },
      ];
      name: "softFreeze";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "uint256";
          name: "_validUntil";
          type: "uint256";
        },
        {
          internalType: "address[]";
          name: "_signers";
          type: "address[]";
        },
        {
          internalType: "bytes[]";
          name: "_signatures";
          type: "bytes[]";
        },
      ];
      name: "unfreeze";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ISecurityCouncil",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISecurityCouncil$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/zk-gov/l1-contracts/src/interfaces/ISecurityCouncil.sol:ISecurityCouncil",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ISecurityCouncil$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ISecurityCouncil",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISecurityCouncil$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/zk-gov/l1-contracts/src/interfaces/ISecurityCouncil.sol:ISecurityCouncil",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ISecurityCouncil$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ISecurityCouncil",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISecurityCouncil$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/zk-gov/l1-contracts/src/interfaces/ISecurityCouncil.sol:ISecurityCouncil",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ISecurityCouncil$Type["abi"]>>;
}
