// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { ProtocolUpgradeHandler$Type } from "./ProtocolUpgradeHandler";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ProtocolUpgradeHandler"]: ProtocolUpgradeHandler$Type;
    ["contracts/zk-gov/l1-contracts/src/ProtocolUpgradeHandler.sol:ProtocolUpgradeHandler"]: ProtocolUpgradeHandler$Type;
  }

  interface ContractTypesMap {
    ["ProtocolUpgradeHandler"]: GetContractReturnType<ProtocolUpgradeHandler$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/ProtocolUpgradeHandler.sol:ProtocolUpgradeHandler"]: GetContractReturnType<
      ProtocolUpgradeHandler$Type["abi"]
    >;
  }
}
