// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { IProtocolUpgradeHandler$Type } from "./IProtocolUpgradeHandler";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IProtocolUpgradeHandler"]: IProtocolUpgradeHandler$Type;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IProtocolUpgradeHandler.sol:IProtocolUpgradeHandler"]: IProtocolUpgradeHandler$Type;
  }

  interface ContractTypesMap {
    ["IProtocolUpgradeHandler"]: GetContractReturnType<IProtocolUpgradeHandler$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IProtocolUpgradeHandler.sol:IProtocolUpgradeHandler"]: GetContractReturnType<
      IProtocolUpgradeHandler$Type["abi"]
    >;
  }
}
