// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { IERC5267$Type } from "./IERC5267";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC5267"]: IERC5267$Type;
    ["@openzeppelin/contracts/interfaces/IERC5267.sol:IERC5267"]: IERC5267$Type;
  }

  interface ContractTypesMap {
    ["IERC5267"]: GetContractReturnType<IERC5267$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC5267.sol:IERC5267"]: GetContractReturnType<
      IERC5267$Type["abi"]
    >;
  }
}
