// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { Guardians$Type } from "./Guardians";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Guardians"]: Guardians$Type;
    ["contracts/zk-gov/l1-contracts/src/Guardians.sol:Guardians"]: Guardians$Type;
  }

  interface ContractTypesMap {
    ["Guardians"]: GetContractReturnType<Guardians$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/Guardians.sol:Guardians"]: GetContractReturnType<
      Guardians$Type["abi"]
    >;
  }
}
