// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { Multisig$Type } from "./Multisig";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Multisig"]: Multisig$Type;
    ["contracts/zk-gov/l1-contracts/src/Multisig.sol:Multisig"]: Multisig$Type;
  }

  interface ContractTypesMap {
    ["Multisig"]: GetContractReturnType<Multisig$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/Multisig.sol:Multisig"]: GetContractReturnType<
      Multisig$Type["abi"]
    >;
  }
}
