// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Multisig$Type {
  _format: "hh-sol-artifact-1";
  contractName: "Multisig";
  sourceName: "contracts/zk-gov/l1-contracts/src/Multisig.sol";
  abi: [
    {
      inputs: [];
      name: "EIP1271_THRESHOLD";
      outputs: [
        {
          internalType: "uint256";
          name: "";
          type: "uint256";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "bytes32";
          name: "_digest";
          type: "bytes32";
        },
        {
          internalType: "address[]";
          name: "_signers";
          type: "address[]";
        },
        {
          internalType: "bytes[]";
          name: "_signatures";
          type: "bytes[]";
        },
        {
          internalType: "uint256";
          name: "_threshold";
          type: "uint256";
        },
      ];
      name: "checkSignatures";
      outputs: [];
      stateMutability: "view";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "bytes32";
          name: "_digest";
          type: "bytes32";
        },
        {
          internalType: "bytes";
          name: "_signature";
          type: "bytes";
        },
      ];
      name: "isValidSignature";
      outputs: [
        {
          internalType: "bytes4";
          name: "";
          type: "bytes4";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "uint256";
          name: "";
          type: "uint256";
        },
      ];
      name: "members";
      outputs: [
        {
          internalType: "address";
          name: "";
          type: "address";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Multisig",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Multisig$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/zk-gov/l1-contracts/src/Multisig.sol:Multisig",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Multisig$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Multisig",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Multisig$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/zk-gov/l1-contracts/src/Multisig.sol:Multisig",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Multisig$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Multisig",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Multisig$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/zk-gov/l1-contracts/src/Multisig.sol:Multisig",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Multisig$Type["abi"]>>;
}
