// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { MessageHashUtils$Type } from "./MessageHashUtils";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MessageHashUtils"]: MessageHashUtils$Type;
    ["@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol:MessageHashUtils"]: MessageHashUtils$Type;
  }

  interface ContractTypesMap {
    ["MessageHashUtils"]: GetContractReturnType<MessageHashUtils$Type["abi"]>;
    ["@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol:MessageHashUtils"]: GetContractReturnType<
      MessageHashUtils$Type["abi"]
    >;
  }
}
