// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { IGuardians$Type } from "./IGuardians";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IGuardians"]: IGuardians$Type;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IGuardians.sol:IGuardians"]: IGuardians$Type;
  }

  interface ContractTypesMap {
    ["IGuardians"]: GetContractReturnType<IGuardians$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IGuardians.sol:IGuardians"]: GetContractReturnType<
      IGuardians$Type["abi"]
    >;
  }
}
