// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { IZKsyncEra$Type } from "./IZKsyncEra";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IZKsyncEra"]: IZKsyncEra$Type;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IZKsyncEra.sol:IZKsyncEra"]: IZKsyncEra$Type;
  }

  interface ContractTypesMap {
    ["IZKsyncEra"]: GetContractReturnType<IZKsyncEra$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IZKsyncEra.sol:IZKsyncEra"]: GetContractReturnType<
      IZKsyncEra$Type["abi"]
    >;
  }
}
