services:
  hh-node:
    platform: linux/amd64
    image: upgrade-checker:local
    command:  sh -c "cd .. && cd e2e && pnpm hardhat node"
    ports:
      - "8545:8545"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'hardhat node' || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 2s
  
  hh-deploy:
    platform: linux/amd64
    image: upgrade-checker:local
    command: sh -c "cd .. && cd e2e && pnpm deploy:setup:remote"
    env_file:
      - .env
    environment:
      L1_RPC_URL: http://hh-node:8545
    depends_on:
      hh-node:
        condition: service_healthy

  db:
    image: postgres:14
    platform: linux/amd64
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webapp
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d webapp"]
      interval: 1s
      timeout: 5s
      retries: 5

  migrate:
    image: upgrade-checker:local
    platform: linux/amd64
    command: sh -c "pnpm db:migrate"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/webapp
    depends_on:
      db:
        condition: service_healthy

  webapp:
    image: upgrade-checker:local
    platform: linux/amd64
    env_file:
      - ../webapp/.env
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/webapp
      L1_RPC_URL: http://hh-node:8545
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      hh-deploy:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully