// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { SignatureChecker$Type } from "./SignatureChecker";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["SignatureChecker"]: SignatureChecker$Type;
    ["@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker"]: SignatureChecker$Type;
  }

  interface ContractTypesMap {
    ["SignatureChecker"]: GetContractReturnType<SignatureChecker$Type["abi"]>;
    ["@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker"]: GetContractReturnType<
      SignatureChecker$Type["abi"]
    >;
  }
}
