// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface SignatureChecker$Type {
  _format: "hh-sol-artifact-1";
  contractName: "SignatureChecker";
  sourceName: "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol";
  abi: [];
  bytecode: "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a14652738ca683aec212b685c4a0381793e93ac13882e0cc159c25a068eb53d364736f6c63430008180033";
  deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220a14652738ca683aec212b685c4a0381793e93ac13882e0cc159c25a068eb53d364736f6c63430008180033";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "SignatureChecker",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureChecker$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<SignatureChecker$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "SignatureChecker",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureChecker$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<SignatureChecker$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "SignatureChecker",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureChecker$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/SignatureChecker.sol:SignatureChecker",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<SignatureChecker$Type["abi"]>>;
}
