// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { IPausable$Type } from "./IPausable";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IPausable"]: IPausable$Type;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IPausable.sol:IPausable"]: IPausable$Type;
  }

  interface ContractTypesMap {
    ["IPausable"]: GetContractReturnType<IPausable$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IPausable.sol:IPausable"]: GetContractReturnType<
      IPausable$Type["abi"]
    >;
  }
}
