// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { TestnetProtocolUpgradeHandler$Type } from "./TestnetProtocolUpgradeHandler";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["TestnetProtocolUpgradeHandler"]: TestnetProtocolUpgradeHandler$Type;
    ["contracts/zk-gov/l1-contracts/src/TestnetProtocolUpgradeHandler.sol:TestnetProtocolUpgradeHandler"]: TestnetProtocolUpgradeHandler$Type;
  }

  interface ContractTypesMap {
    ["TestnetProtocolUpgradeHandler"]: GetContractReturnType<
      TestnetProtocolUpgradeHandler$Type["abi"]
    >;
    ["contracts/zk-gov/l1-contracts/src/TestnetProtocolUpgradeHandler.sol:TestnetProtocolUpgradeHandler"]: GetContractReturnType<
      TestnetProtocolUpgradeHandler$Type["abi"]
    >;
  }
}
