// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { IL2Governor$Type } from "./IL2Governor";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IL2Governor"]: IL2Governor$Type;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IL2Governor.sol:IL2Governor"]: IL2Governor$Type;
  }

  interface ContractTypesMap {
    ["IL2Governor"]: GetContractReturnType<IL2Governor$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IL2Governor.sol:IL2Governor"]: GetContractReturnType<
      IL2Governor$Type["abi"]
    >;
  }
}
