// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { Strings$Type } from "./Strings";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Strings"]: Strings$Type;
    ["@openzeppelin/contracts/utils/Strings.sol:Strings"]: Strings$Type;
  }

  interface ContractTypesMap {
    ["Strings"]: GetContractReturnType<Strings$Type["abi"]>;
    ["@openzeppelin/contracts/utils/Strings.sol:Strings"]: GetContractReturnType<
      Strings$Type["abi"]
    >;
  }
}
