// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Strings$Type {
  _format: "hh-sol-artifact-1";
  contractName: "Strings";
  sourceName: "@openzeppelin/contracts/utils/Strings.sol";
  abi: [
    {
      inputs: [
        {
          internalType: "uint256";
          name: "value";
          type: "uint256";
        },
        {
          internalType: "uint256";
          name: "length";
          type: "uint256";
        },
      ];
      name: "StringsInsufficientHexLength";
      type: "error";
    },
  ];
  bytecode: "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122022ea8e82b761ff0f2c8fae5d36bcca20db5176a1081cc893147086b57be5cf8f64736f6c63430008180033";
  deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122022ea8e82b761ff0f2c8fae5d36bcca20db5176a1081cc893147086b57be5cf8f64736f6c63430008180033";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Strings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Strings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Strings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Strings$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Strings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/Strings.sol:Strings",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Strings$Type["abi"]>>;
}
