// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { ShortStrings$Type } from "./ShortStrings";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ShortStrings"]: ShortStrings$Type;
    ["@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings"]: ShortStrings$Type;
  }

  interface ContractTypesMap {
    ["ShortStrings"]: GetContractReturnType<ShortStrings$Type["abi"]>;
    ["@openzeppelin/contracts/utils/ShortStrings.sol:ShortStrings"]: GetContractReturnType<
      ShortStrings$Type["abi"]
    >;
  }
}
