// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { IStateTransitionManager$Type } from "./IStateTransitionManager";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IStateTransitionManager"]: IStateTransitionManager$Type;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IStateTransitionManager.sol:IStateTransitionManager"]: IStateTransitionManager$Type;
  }

  interface ContractTypesMap {
    ["IStateTransitionManager"]: GetContractReturnType<IStateTransitionManager$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/interfaces/IStateTransitionManager.sol:IStateTransitionManager"]: GetContractReturnType<
      IStateTransitionManager$Type["abi"]
    >;
  }
}
