// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface IStateTransitionManager$Type {
  _format: "hh-sol-artifact-1";
  contractName: "IStateTransitionManager";
  sourceName: "contracts/zk-gov/l1-contracts/src/interfaces/IStateTransitionManager.sol";
  abi: [
    {
      inputs: [
        {
          internalType: "uint256";
          name: "_chainId";
          type: "uint256";
        },
      ];
      name: "freezeChain";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
    {
      inputs: [];
      name: "getAllHyperchainChainIDs";
      outputs: [
        {
          internalType: "uint256[]";
          name: "";
          type: "uint256[]";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
    {
      inputs: [
        {
          internalType: "uint256";
          name: "_chainId";
          type: "uint256";
        },
      ];
      name: "unfreezeChain";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "IStateTransitionManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IStateTransitionManager$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/zk-gov/l1-contracts/src/interfaces/IStateTransitionManager.sol:IStateTransitionManager",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<IStateTransitionManager$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "IStateTransitionManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IStateTransitionManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/zk-gov/l1-contracts/src/interfaces/IStateTransitionManager.sol:IStateTransitionManager",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<IStateTransitionManager$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "IStateTransitionManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IStateTransitionManager$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/zk-gov/l1-contracts/src/interfaces/IStateTransitionManager.sol:IStateTransitionManager",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<IStateTransitionManager$Type["abi"]>>;
}
