import { range } from "./range.js";

export const COUNCIL_SIZE = 12;
export const GUARDIANS_SIZE = 8;

export const DERIVATION_INDEXES = {
  FIRST_COUNCIL: 0,
  FIRST_GUARDIAN: 1,
  ZK_FOUNDATION: 2,
  VISITOR: 3,
  SECOND_COUNCIL: 4,
  SECOND_GUARDIAN: 4 + COUNCIL_SIZE - 1,
} as const;

export const ALL_COUNCIL_INDEXES = [DERIVATION_INDEXES.FIRST_COUNCIL, ...range(DERIVATION_INDEXES.SECOND_COUNCIL, COUNCIL_SIZE - 1)]
export const ALL_GUARDIAN_INDEXES = [DERIVATION_INDEXES.FIRST_GUARDIAN, ...range(DERIVATION_INDEXES.SECOND_GUARDIAN, GUARDIANS_SIZE - 1)]
