name: Workflow template for testing e2e jobs
on:
  workflow_call:

env:
  FORCE_COLOR: 1

defaults:
  run:
    working-directory: ./packages/e2e

jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm test:cli

  test-e2e-web:
    runs-on: ubuntu-latest
    env:
      HEADLESS: false
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm test:web:env:up
      - run: xvfb-run pnpm playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30
      - if: always()
        run: pnpm test:web:env:down
      - name: App logs
        if: always()
        run: cat ./logs/app.log
      - name: Main node logs
        if: always()
        run: cat ./logs/main-node.log
      - name: Backup node logs
        if: always()
        run: cat ./logs/backup-node.log
