name: Workflow template for testing e2e jobs
on:
  workflow_call:
    secrets:
      ETHERSCAN_API_KEY:
        required: true

env:
  FORCE_COLOR: 1

defaults:
  run:
    working-directory: ./packages/e2e

jobs:
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: cd ../../apps/cli && pnpm build
      - run: cp .env.example .env
      - env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
        run: pnpm test:cli

  test-e2e-web:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: webapp
        ports:
          - 5432:5432
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      HEADLESS: false
      WALLET_CONNECT_PROJECT_ID: placeholder
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm playwright install --with-deps chromium
      - run: cd ../contracts && pnpm build
      - run: pnpm test:web:env:up
      - run: xvfb-run pnpm playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: packages/e2e/playwright-report/
          retention-days: 30
      - if: always()
        run: pnpm test:web:env:down
      - name: App logs
        if: always()
        run: cat ./logs/app.log
      - name: Main node logs
        if: always()
        run: cat ./logs/main-node.log
      - name: Backup node logs
        if: always()
        run: cat ./logs/backup-node.log
