// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { EmergencyUpgradeBoard$Type } from "./EmergencyUpgradeBoard";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EmergencyUpgradeBoard"]: EmergencyUpgradeBoard$Type;
    ["contracts/zk-gov/l1-contracts/src/EmergencyUpgradeBoard.sol:EmergencyUpgradeBoard"]: EmergencyUpgradeBoard$Type;
  }

  interface ContractTypesMap {
    ["EmergencyUpgradeBoard"]: GetContractReturnType<EmergencyUpgradeBoard$Type["abi"]>;
    ["contracts/zk-gov/l1-contracts/src/EmergencyUpgradeBoard.sol:EmergencyUpgradeBoard"]: GetContractReturnType<
      EmergencyUpgradeBoard$Type["abi"]
    >;
  }
}
