// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { EIP712$Type } from "./EIP712";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EIP712"]: EIP712$Type;
    ["@openzeppelin/contracts/utils/cryptography/EIP712.sol:EIP712"]: EIP712$Type;
  }

  interface ContractTypesMap {
    ["EIP712"]: GetContractReturnType<EIP712$Type["abi"]>;
    ["@openzeppelin/contracts/utils/cryptography/EIP712.sol:EIP712"]: GetContractReturnType<
      EIP712$Type["abi"]
    >;
  }
}
