// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface EIP712$Type {
  _format: "hh-sol-artifact-1";
  contractName: "EIP712";
  sourceName: "@openzeppelin/contracts/utils/cryptography/EIP712.sol";
  abi: [
    {
      inputs: [];
      name: "InvalidShortString";
      type: "error";
    },
    {
      inputs: [
        {
          internalType: "string";
          name: "str";
          type: "string";
        },
      ];
      name: "StringTooLong";
      type: "error";
    },
    {
      anonymous: false;
      inputs: [];
      name: "EIP712DomainChanged";
      type: "event";
    },
    {
      inputs: [];
      name: "eip712Domain";
      outputs: [
        {
          internalType: "bytes1";
          name: "fields";
          type: "bytes1";
        },
        {
          internalType: "string";
          name: "name";
          type: "string";
        },
        {
          internalType: "string";
          name: "version";
          type: "string";
        },
        {
          internalType: "uint256";
          name: "chainId";
          type: "uint256";
        },
        {
          internalType: "address";
          name: "verifyingContract";
          type: "address";
        },
        {
          internalType: "bytes32";
          name: "salt";
          type: "bytes32";
        },
        {
          internalType: "uint256[]";
          name: "extensions";
          type: "uint256[]";
        },
      ];
      stateMutability: "view";
      type: "function";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "EIP712",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EIP712$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/EIP712.sol:EIP712",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<EIP712$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "EIP712",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EIP712$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/EIP712.sol:EIP712",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<EIP712$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "EIP712",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EIP712$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/EIP712.sol:EIP712",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<EIP712$Type["abi"]>>;
}
