// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import type { ICounter$Type } from "./ICounter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ICounter"]: ICounter$Type;
    ["contracts/local-contracts/dev/ICounter.sol:ICounter"]: ICounter$Type;
  }

  interface ContractTypesMap {
    ["ICounter"]: GetContractReturnType<ICounter$Type["abi"]>;
    ["contracts/local-contracts/dev/ICounter.sol:ICounter"]: GetContractReturnType<
      ICounter$Type["abi"]
    >;
  }
}
