// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ICounter$Type {
  _format: "hh-sol-artifact-1";
  contractName: "ICounter";
  sourceName: "contracts/local-contracts/dev/ICounter.sol";
  abi: [
    {
      inputs: [
        {
          internalType: "uint256";
          name: "";
          type: "uint256";
        },
      ];
      name: "setNumber";
      outputs: [];
      stateMutability: "nonpayable";
      type: "function";
    },
  ];
  bytecode: "0x";
  deployedBytecode: "0x";
  linkReferences: {};
  deployedLinkReferences: {};
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ICounter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ICounter$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/local-contracts/dev/ICounter.sol:ICounter",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ICounter$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ICounter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ICounter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/local-contracts/dev/ICounter.sol:ICounter",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ICounter$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ICounter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ICounter$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/local-contracts/dev/ICounter.sol:ICounter",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ICounter$Type["abi"]>>;
}
